#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

S2I_EXE=s2i
if [ -z $(type -P "$S2I_EXE") ]; then
  echo -e "The ${S2I_EXE} executable is needed and not on your path."
  echo -e "It can be downloaded from here: https://github.com/openshift/source-to-image"
  echo -e "Make sure you place it in a directory on your path."
  exit 1
fi

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME-fla}"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

  Usage: $0 {start|stop|build|rm}

  Options:

  build - Build the docker images for the project.
          You need to do this first, since the builds require
          a combination of Docker and S2I builds.

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yml file.

          You can pass in a list of containers to start.  
          By default all containers will be started.
          
          The API_URL used by fla-web can also be redirected.

          Examples:
          $0 start
          $0 start fla-web
          $0 start fla-web API_URL=http://docker.for.win.localhost:56325/api/v1

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.

  rm - Removes any existing application containers.
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings:
# -----------------------------------------------------------------------------------------------------------------
DEFAULT_CONTAINERS="fla-db fla-api schema-spy fla-web fla-pdf"
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
build-all() {
  build-web
  build-db
  build-schema-spy
  build-api
  build-pdf
}

build-web() {
  #
  # fla-web
  #
  # The fla-runtime image is used for the final runtime image.
  # The fla-web-artifacts image is used to build the artifacts for the vue distribution.
  # The fla-web image is copy of the fla-runtime image complete with a copy of the build artifacts.
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building the fla-runtime image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t 'fla-runtime' \
    -f './nginx-runtime/Dockerfile' './nginx-runtime/'
  echo -e "===================================================================================================="
  
  echo -e "\n\n===================================================================================================="
  echo -e "Building the fla-web-artifacts image using s2i (WEB_BASE_HREF: '${WEB_BASE_HREF}') ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  ${S2I_EXE} build \
    --copy \
    -e WEB_BASE_HREF=${WEB_BASE_HREF} \
    '../web' \
    'centos/nodejs-10-centos7:10' \
    'fla-web-artifacts'
  echo -e "===================================================================================================="

  echo -e "\n\n===================================================================================================="
  echo -e "Building the fla-web image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t 'fla-web' \
    -f './vue-on-nginx/Dockerfile' './vue-on-nginx/'
  echo -e "===================================================================================================="
}

build-web-dev() {
  #
  # web-dev
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building the fla-runtime image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t 'fla-runtime' \
    -f './nginx-runtime/Dockerfile' './nginx-runtime/'
  echo -e "===================================================================================================="

  echo -e "\n\n===================================================================================================="
  echo -e "Building the fla-web-dev image using s2i ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  ${S2I_EXE} build \
    --copy \
    -e "DEV_MODE=true" \
    '../web' \
    'centos/nodejs-10-centos7:10' \
    'fla-web-dev'
  echo -e "===================================================================================================="
}

build-db() {
  #
  # fla-db
  #
  # Nothing to build here ...
  echo
}

build-schema-spy() {
  #
  # schema-spy
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building schema-spy image ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    https://github.com/bcgov/SchemaSpy.git \
    -t 'schema-spy'
  echo -e "===================================================================================================="
}

build-api() {
  #
  # fla-api
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building fla-api image using s2i ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  ${S2I_EXE} build \
    --copy \
    '../api' \
    'centos/python-36-centos7' \
    'fla-api'
  echo -e "===================================================================================================="
}

build-pdf() {
  #
  # fla-pdf
  #
  # Nothing to build here ...
  echo
}

configureEnvironment () {
  for arg in $@; do
    case "$arg" in
      *=*)
        export ${arg}
        ;;  
    esac
  done
  
  # fla-db
  export POSTGRESQL_DATABASE="FAMILY_PROTECTION_ORDER"
  export POSTGRESQL_USER="DB_USER"
  export POSTGRESQL_PASSWORD="DB_PASSWORD"
  export POSTGRESQL_ADMIN_PASSWORD="DB_ADMIN_PASSWORD"

  # schema-spy
  export DATABASE_SERVICE_NAME="fla-db"
  export POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
  export POSTGRESQL_USER=${POSTGRESQL_USER}
  export POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}

  # fla-api
  export API_HTTP_PORT=${API_HTTP_PORT-8081}
  export PDF_SERVICE_URL=${PDF_SERVICE_URL-http://fla-pdf:5001}
  export OVERRIDE_USER_ID=${OVERRIDE_USER_ID-}
  export DATABASE_SERVICE_NAME="fla-db"
  export DATABASE_ENGINE="postgresql"
  export DATABASE_NAME=${POSTGRESQL_DATABASE}
  export DATABASE_USER=${POSTGRESQL_USER}
  export DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
  export DJANGO_SECRET_KEY=wpn1GZrouOryH2FshRrpVHcEhMfMLtmTWMC2K5Vhx8MAi74H5y
  export DJANGO_DEBUG=True
  export DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL-INFO}
  export EFILING_AUTH_URL=${EFILING_AUTH_URL}
  export EFILING_CLIENT_ID=${EFILING_CLIENT_ID}
  export EFILING_CLIENT_SECRET=${EFILING_CLIENT_SECRET}
  export EFILING_BASE_URL=${EFILING_BASE_URL}
  export FRONT_END=${FRONT_END-prod}
  export DATA_SECURITY_KEY=${DATA_SECURITY_KEY-01234567890123456789012345678901}

  # fla-web
  export WEB_HTTP_PORT=${WEB_HTTP_PORT-8080}
  export API_URL=${API_URL-http://fla-api:8080/api}
  export WEB_BASE_HREF=${WEB_BASE_HREF:-/apply-for-family-order/}
  export IpFilterRules='#allow all; deny all;'
  export RealIpFrom='127.0.0.0/16'
}

getStartupParams() {
  CONTAINERS=""
  ARGS="--force-recreate"

  for arg in $@; do
    case "$arg" in
      *=*)
        # Skip it
        ;;  
     -*)
        ARGS+=" $arg";;
      *)
        CONTAINERS+=" $arg";;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
    CONTAINERS="$DEFAULT_CONTAINERS"
  fi

  echo ${ARGS} ${CONTAINERS}
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose rm -svf >/dev/null

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} |  xargs docker volume rm
  else
    echo "No project volumes exist."
  fi
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}

clean() {
  docker rmi --force fla-runtime fla-web-artifacts fla-web fla-web-dev fla-api
  docker image prune --force
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift

case "$COMMAND" in
  start)
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;
  web-dev)
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    [ -z "$SKIP_BUILD" ] && build-web-dev
    docker-compose run --rm --service-ports fla-web-dev
    ;;
  stop)
    configureEnvironment $@
    docker-compose stop
    ;;
  rm|down)
    configureEnvironment $@
    deleteVolumes
    ;;
  clean)
    configureEnvironment $@
    clean
    ;;
  build)
    buildImage=$(toLower ${1})
    shift || buildImage=all
    buildImage=$(echo ${buildImage} | sed s~^fla-~~)
    case "$buildImage" in
      *=*)
        buildImage=all
        ;;
    esac

    if functionExists "build-${buildImage}"; then
      configureEnvironment $@
      eval "build-${buildImage}"
    else
      echo -e "Error:\nThe build function, build-${buildImage}, does not exist.  Please check your build parameters and try again.\nUse '-h' to get full help details."
      exit 1
    fi
    ;;
  *)
    usage
esac

popd >/dev/null
