# Generated by Django 3.1.2 on 2020-12-02 18:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200929_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
