# Generated by Django 3.1.4 on 2020-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla', '0007_auto_20201204_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
