<template>
    <div>    
        <b-card v-if="dataReady" bg-variant="white" border-variant="white">

            <b-row>
                There are issues with the document(s) that you submitted for filing.   
                Below is the list of document(s) you submitted along with the status of the document(s).
            </b-row>

            <b-row>
                Please review this 
                <a style='display:inline' class="text-danger mx-1 inline" @click="downloadNotice()">
                    <u style="cursor:pointer; display:inline" >REGISTRY NOTICE</u>
                </a> which will display the comments made by registry 
                staff identifying where additional information or corrections are required.
            </b-row>

            <b-row>
                If you are not certain how to correct your application, you may want to get some 
                legal advise before you submit your corrected document(s) for filing.
            </b-row>

            <b-row>
                <div class="m-1 text-primary" @click="showLegalAssistance= !showLegalAssistance" style="border-bottom:1px solid; width:19rem;">
                    <span style='font-size:1.2rem;' class="fa fa-question-circle" /> Where can I get legal assistance? 
                    <span v-if="showLegalAssistance" class='ml-2 fa fa-chevron-up'/>
                    <span v-if="!showLegalAssistance" class='ml-2 fa fa-chevron-down'/>
                </div>
                <legal-assistance-faq v-if="showLegalAssistance"/>
            </b-row>

            <b-row>
                <!-- TODO: place the documents and their stasuses here -->
            </b-row>

            <h2 class="mt-4 text-primary">OPTIONS:</h2> 

            <ol>
                <li>
                    
                    <p v-if="attachedOnly">
                        If you wish to proceed to correct the document(s) requiring action, 
                        you  will need to make the necessary changes and then click on the 
                        correct button to upload and submit them.
                    </p>
                    <p v-else>
                        If you wish to proceed to correct the document(s) requiring action, 
                        you can click the button to edit the existing information in the 
                        document and then proceed to resubmit the document(s) for filing.
                    </p>
                    
                    <b-button 
                        style="display: block;"
                        class="ml-auto mr-3 mb-2 bg-success"
                        size="md" 
                        variant="success" 
                        @click="correctApplication()">
                        Correct Application
                        <b-icon-pencil-fill scale="1" variant="white"/>
                    </b-button>

                    <p>
                        <b>NOTE:</b>  When you resubmit your document, it will be assigned 
                        a new package number that you will need to note to track the 
                        status of your resubmitted document.
                    </p>
                </li>
                
                <li>
                    <p v-if="attachedOnly">
                        You can opt to start a new submission if you prefer or can file 
                        manually at the court registry.
                    </p>
                    <p>
                        You can opt to start your document(s) over again but note that you 
                        will need to re-enter all information into the form.
                    </p>
                    
                </li>
                <!-- TODO: display the last option only if there are also attached documents with issues -->
                <li>
                    Some documents identified were not generated by this application, 
                    so you will need to correct those documents and upload them with 
                    any other documents.  You can do this during the submit process.
                </li>
            </ol>          
        
        </b-card>
        <loading-spinner v-else waitingText="Waiting for submitted information"/>  
    </div>   
</template>

<script lang="ts">    
import { Component, Prop, Vue } from 'vue-property-decorator';
import { namespace } from "vuex-class";

import "@/store/modules/common";
import { locationsInfoType } from '@/types/Common';
const commonState = namespace("Common");

import LegalAssistanceFaq from "@/components/utils/LegalAssistanceFaq.vue";


@Component({
    components:{  
        LegalAssistanceFaq
        
    }
})
export default class RejectedPackageInstructions extends Vue {

    @Prop({required: true})
    applicationId!: string;

    @commonState.State
    public locationsInfo!: locationsInfoType[];

  

    dataReady = false;
    showLegalAssistance = false;
    generatedOnly = false;
    attachedOnly = false;
    generatedAttached = false;
    
  
    error = ''

    mounted(){
        this.dataReady = false;
        this.showLegalAssistance = false;
        this.getApplicationInfo(this.applicationId);        
    } 

    public getApplicationInfo(applicationId) { 

        //TODO: get the rejection data and determine whether it's one of the following:
        //generatedOnly
        //attachedOnly
        //generatedAttached


        this.$http.get('/app/'+ applicationId + '/')
        .then((response) => {

            const applicationData = response.data;
            // console.log(applicationData)  
           
            const stepGETSTART = this.getStepResultByName(applicationData, 'GETSTART');
            const apps = stepGETSTART.submittedPdfList;

            this.generatedOnly = false;
            this.attachedOnly = false;
            this.generatedAttached = false;  
            
            Vue.nextTick(()=> this.dataReady = true);

        }, err => {
            this.error = err;        
        });
    }
    
    public getStepResultByName(applicationData, stepName){
        if(applicationData?.steps){
            const steps = applicationData.steps.filter(step => step.name == stepName);
            if(steps.length == 1) return steps[0].result
        }
        return {}
    }
       
    public getFullName(formType){
        return Vue.filter('pdfTypeToFullName')(formType)
    }

    public downloadNotice(){
        console.log('downloading')
        //TODO: add download api
    }

    public correctApplication(){

        //TODO: update the code below and if possible resume on where there was a mistake

        // this.$http.get('/app/'+ this.applicationId + '/')
        // .then((response) => {

        //     const applicationData = response.data   
        //     const applicationType = (applicationData.type?.length>0)?this.extractTypes(applicationData.type.split(',')):[];          
            
        //     const storeMigrationFn = new MigrateStore()           
        //     this.currentApplication = storeMigrationFn.migrate(applicationData, applicationType, Vue.filter('get-current-version')())

        //     const comStepFn = new RestoreCommonStep()
        //     comStepFn.restore(this.currentApplication)
           
        //     this.checkAllCompleted();
           
        //     this.$router.push({name: "flapp-surveys" }) 

        // }, err => {
        //     this.error = err;        
        // });

    }

}
</script>

<style scoped lang="scss">

    .help-header {
        color: #036;
    }
   
</style>