# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_surveyresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
