# Generated by Django 2.1.15 on 2020-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200908_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='respondent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
