# Generated by Django 3.1.1 on 2020-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200917_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='universal_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
