# Generated by Django 2.1.15 on 2020-09-14 05:17

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200909_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_name',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='s_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='all_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='clickable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.Step'),
        ),
        migrations.AlterField(
            model_name='preparedpdf',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Application'),
        ),
    ]
