# Generated by Django 2.1.15 on 2020-09-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200909_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='api.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.Application'),
        ),
    ]
