# Generated by Django 3.1.1 on 2020-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_universal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='preparedpdf',
            name='key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
