# Generated by Django 3.1.6 on 2021-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedpdf',
            name='json_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
