# Generated by Django 3.1.6 on 2021-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_application_last_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
