# Generated by Django 3.1.6 on 2021-03-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_application_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='location',
        ),
    ]
