# Generated by Django 3.1.6 on 2021-03-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_application_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_filed',
        ),
        migrations.CreateModel(
            name='EFilingSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('submission_id', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('package_number', models.CharField(max_length=100, null=True)),
                ('package_url', models.CharField(max_length=200, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efiling_submission_application_id', to='api.application')),
            ],
        ),
    ]
