# Generated by Django 3.1.6 on 2021-03-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210302_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_submission_id',
        ),
        migrations.AddField(
            model_name='application',
            name='last_efiling_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_application_id', to='api.efilingsubmission'),
        ),
    ]
