# Generated by Django 3.1.7 on 2021-04-13 16:12

from django.db import migrations, models
import django.db.models.deletion


def add_application_id_to_prepared_pdf(apps, schema_editor):
    PreparedPdf = apps.get_model("api", "PreparedPdf")
    Application = apps.get_model("api", "Application")

    for application in Application.objects.all():
        pdf = PreparedPdf.objects.filter(id=application.prepared_pdf_id).first()
        if pdf:
            pdf.application_id = application.id
            pdf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210302_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedpdf',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_pdf_application_id', to='api.application'),
        ),
        migrations.RunPython(add_application_id_to_prepared_pdf)
    ]
