# Generated by Django 3.1.7 on 2021-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_application_id_to_prepared_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='prepared_pdf',
        ),
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='preparedpdf',
            name='pdf_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='preparedpdf',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='preparedpdf',
            constraint=models.UniqueConstraint(fields=('application_id', 'pdf_type'), name='unique_pdf_type_application_id'),
        ),
    ]
