# Generated by Django 3.1.7 on 2021-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idir_userid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
