# Generated by Django 3.1.7 on 2021-05-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_idir_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='protected_child_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='protected_party_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='respondent_name',
        ),
    ]
