# Generated by Django 3.1.7 on 2021-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_hide_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_efiling_early_adopters',
            field=models.BooleanField(default=False),
        ),
    ]
