# Generated by Django 4.0.7 on 2023-07-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_typescript_model_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingsubmission',
            name='key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='efilingsubmission',
            name='submission_results',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
