// This Jenkins file uses a brute force method to promote the application images from TEST to PROD.
// In other words all of the images that are currently deployed in TEST will be tagged for deployment to PROD.

// Define these in the order they should be deployed.
// Do not deploy schema-spy into prod
def APP_NAMES = ['db', 'api', 'web', 'pdf', 'backup']
def SOURCE_TAG = 'test'
def DESTINATION_TAG = 'prod'

node {
  APP_NAMES.each { appName ->
    stage("Deploying ${appName} to ${DESTINATION_TAG}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Tagging ${appName}:${SOURCE_TAG} for deployment to ${DESTINATION_TAG} ..."
            openshift.tag("${appName}:${SOURCE_TAG}", "${appName}:${DESTINATION_TAG}")
          }
        }
      }
    }
  }
}